apiVersion: v1
kind: Pod
metadata:
  namespace: ashu-space 
  creationTimestamp: null
  labels:
    run: ashupod2
  name: ashupod2  # name of the pod 
spec:
  containers:
  - image: nginx
    name: ashupod2
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
